// <auto-generated />
using System;
using MPMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MPMS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260315000000_SplitUserNameToFirstLast")]
    partial class SplitUserNameToFirstLast
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot is in ApplicationDbContextModelSnapshot
        }
    }
}
