// <auto-generated />
using System;
using MPMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MPMS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316000000_AddAvatarDataToUsers")]
    partial class AddAvatarDataToUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");
#pragma warning restore 612, 618
        }
    }
}
